// Code generated by counterfeiter. DO NOT EDIT.
package seeded_fakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures/seeded"
)

type FakeSower struct {
	SowStub        func(string) (int, error)
	sowMutex       sync.RWMutex
	sowArgsForCall []struct {
		arg1 string
	}
	sowReturns struct {
		result1 int
		result2 error
	}
	sowReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSower) Sow(arg1 string) (int, error) {
	fake.sowMutex.Lock()
	ret, specificReturn := fake.sowReturnsOnCall[len(fake.sowArgsForCall)]
	fake.sowArgsForCall = append(fake.sowArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SowStub
	fakeReturns := fake.sowReturns
	fake.recordInvocation("Sow", []interface{}{arg1})
	fake.sowMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSower) SowCallCount() int {
	fake.sowMutex.RLock()
	defer fake.sowMutex.RUnlock()
	return len(fake.sowArgsForCall)
}

func (fake *FakeSower) SowCalls(stub func(string) (int, error)) {
	fake.sowMutex.Lock()
	defer fake.sowMutex.Unlock()
	fake.SowStub = stub
}

func (fake *FakeSower) SowArgsForCall(i int) string {
	fake.sowMutex.RLock()
	defer fake.sowMutex.RUnlock()
	argsForCall := fake.sowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSower) SowReturns(result1 int, result2 error) {
	fake.sowMutex.Lock()
	defer fake.sowMutex.Unlock()
	fake.SowStub = nil
	fake.sowReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeSower) SowReturnsOnCall(i int, result1 int, result2 error) {
	fake.sowMutex.Lock()
	defer fake.sowMutex.Unlock()
	fake.SowStub = nil
	if fake.sowReturnsOnCall == nil {
		fake.sowReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.sowReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeSower) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSower) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ seeded.Sower = new(FakeSower)
