package generator

import (
	"bytes"
	"fmt"
	"go/build"
	"go/types"
	"io"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

func (f *Fake) loadPackages(c Cacher, workingDir string) error {
	log.Println("loading packages...")
	p, ok := c.Load(f.TargetPackage)
	if ok {
		f.Packages = p
		log.Printf("loaded %v packages from cache\n", len(f.Packages))
		return nil
	}
	importPath := f.TargetPackage
	if !filepath.IsAbs(importPath) {
		ctx := getBuildContext(workingDir)
		bp, err := ctx.Import(f.TargetPackage, workingDir, build.FindOnly)
		if err != nil {
			return err
		}
		importPath = bp.ImportPath
	}
	p, err := packages.Load(&packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedImports | packages.NeedTypes | packages.NeedSyntax,
		Dir:   workingDir,
		Tests: true,
	}, importPath)
	if err != nil {
		return err
	}
	for i := range p {
		for j := range p[i].Errors {
			e := p[i].Errors[j]
			if isBuildTranscript(e) {
				// go list -export reports a package that failed to
				// compile as a single error holding the compiler's
				// output. go/packages then type-checks that package
				// from source, and those positioned errors are the
				// ones we act on.
				log.Printf("ignoring build failure, package was type-checked from source: %v", strings.TrimPrefix(fmt.Sprintf("%v", e), "-: "))
				continue
			}
			if isErrorInGeneratedFake(e) {
				// A fake generated into the target package that no longer
				// matches its interface must not block regenerating it.
				log.Printf("ignoring error in stale fake: %v", strings.TrimPrefix(fmt.Sprintf("%v", e), "-: "))
				continue
			}
			if i == 0 && err == nil {
				err = e
			}
			log.Printf("error loading packages: %v", strings.TrimPrefix(fmt.Sprintf("%v", e), "-: "))
		}
	}
	if err != nil {
		return err
	}
	f.Packages = p
	c.Store(f.TargetPackage, p)
	log.Printf("loaded %v packages\n", len(f.Packages))
	return nil
}

func (f *Fake) findPackage() error {
	var target *types.TypeName
	var pkg *packages.Package
	for i := range f.Packages {
		if f.Packages[i].Types == nil || f.Packages[i].Types.Scope() == nil {
			continue
		}
		pkg = f.Packages[i]
		if f.Mode == Package {
			break
		}

		raw := pkg.Types.Scope().Lookup(f.TargetName)
		if raw != nil {
			if typeName, ok := raw.(*types.TypeName); ok {
				target = typeName
				break
			}
		}
		pkg = nil
	}
	if pkg == nil {
		switch f.Mode {
		case Package:
			return fmt.Errorf("cannot find package with name: %s", f.TargetPackage)
		case InterfaceOrFunction:
			return fmt.Errorf("cannot find package with target: %s", f.TargetName)
		}
	}
	f.Target = target
	f.Package = pkg
	f.TargetPackage = imports.VendorlessPath(pkg.PkgPath)
	f.inTargetPackage = sameDir(f.DestinationDir, packageDir(pkg))
	if !f.inTargetPackage {
		t := f.Imports.Add(pkg.Name, f.TargetPackage)
		f.TargetAlias = t.Alias
	}
	if f.Mode != Package {
		f.TargetName = target.Name()
	}
	f.loadGenericTypeParams()

	if f.Mode == InterfaceOrFunction {
		if !f.IsInterface() && !f.IsFunction() {
			return fmt.Errorf("cannot generate a fake for %s because it is not an interface or function", f.TargetName)
		}

		if f.IsConstraintInterface() {
			return fmt.Errorf("cannot generate a fake for %s because it is a constraint interface (contains type constraints like ~string) which cannot be implemented by concrete types", f.TargetName)
		}
	}

	if f.IsInterface() {
		log.Printf("Found interface with name: [%s]\n", f.TargetName)
	}
	if f.IsFunction() {
		log.Printf("Found function with name: [%s]\n", f.TargetName)
	}
	if f.Mode == Package {
		log.Printf("Found package with name: [%s]\n", f.TargetPackage)
	}
	return nil
}

// generatedFakeHeader is the marker line written at the top of every fake.
const generatedFakeHeader = "// Code generated by counterfeiter. DO NOT EDIT."

// isBuildTranscript reports whether a package loading error is the
// compiler output that go list -export attaches to a package it could not
// build, as opposed to a positioned error about a specific file.
func isBuildTranscript(e packages.Error) bool {
	return e.Kind == packages.ListError && e.Pos == "" && strings.HasPrefix(e.Msg, "# ")
}

// isErrorInGeneratedFake reports whether a package loading error is
// positioned inside a file that counterfeiter generated.
func isErrorInGeneratedFake(e packages.Error) bool {
	filename := errorFilename(e.Pos)
	if filename == "" {
		return false
	}
	fh, err := os.Open(filename)
	if err != nil {
		return false
	}
	defer fh.Close()
	head := make([]byte, 4096)
	n, _ := io.ReadFull(fh, head)
	return bytes.Contains(head[:n], []byte(generatedFakeHeader))
}

// errorFilename strips the ":line" and ":line:col" suffixes from a
// packages.Error position, leaving the file path.
func errorFilename(pos string) string {
	for range 2 {
		i := strings.LastIndex(pos, ":")
		if i < 0 {
			break
		}
		if _, err := strconv.Atoi(pos[i+1:]); err != nil {
			break
		}
		pos = pos[:i]
	}
	if pos == "" || pos == "-" {
		return ""
	}
	return pos
}

// packageDir returns the directory holding the package's source files.
func packageDir(pkg *packages.Package) string {
	if pkg.Dir != "" {
		return pkg.Dir
	}
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0])
	}
	return ""
}

// sameDir reports whether a and b name the same directory. Either being
// empty means "unknown", which never matches.
func sameDir(a, b string) bool {
	if a == "" || b == "" {
		return false
	}
	return canonicalDir(a) == canonicalDir(b)
}

func canonicalDir(dir string) string {
	if resolved, err := filepath.EvalSymlinks(dir); err == nil {
		dir = resolved
	}
	if abs, err := filepath.Abs(dir); err == nil {
		dir = abs
	}
	return filepath.Clean(dir)
}

// loadGenericTypeParams records the type parameter list of a generic
// interface target, in both the declaration form ("[T pkg.Constraint]") and
// the instantiation form ("[T]"). Constraints are rendered with the same
// qualifier as method signatures, so any package they refer to is imported
// and aliased consistently. It must run after the target package has been
// added to f.Imports.
func (f *Fake) loadGenericTypeParams() {
	if f.Target == nil {
		return
	}
	named, ok := f.Target.Type().(*types.Named)
	if !ok {
		return
	}
	if _, ok := named.Underlying().(*types.Interface); !ok {
		return
	}
	typeParams := named.TypeParams()
	if typeParams.Len() == 0 {
		return
	}
	names := make([]string, 0, typeParams.Len())
	namesAndConstraints := make([]string, 0, typeParams.Len())
	for i := 0; i < typeParams.Len(); i++ {
		param := typeParams.At(i)
		f.addImportsFor(param.Constraint())
		constraint := types.TypeString(param.Constraint(), f.Imports.AliasForPackage)
		names = append(names, param.Obj().Name())
		namesAndConstraints = append(namesAndConstraints, param.Obj().Name()+" "+constraint)
	}
	f.GenericTypeParameters = "[" + strings.Join(names, ", ") + "]"
	f.GenericTypeParametersAndConstraints = "[" + strings.Join(namesAndConstraints, ", ") + "]"
}

// addImportsFor inspects the given type and adds imports to the fake if importable
// types are found.
func (f *Fake) addImportsFor(typ types.Type) {
	if typ == nil {
		return
	}

	switch t := typ.(type) {
	case *types.Basic:
		return
	case *types.Pointer:
		f.addImportsFor(t.Elem())
	case *types.Map:
		f.addImportsFor(t.Key())
		f.addImportsFor(t.Elem())
	case *types.Chan:
		f.addImportsFor(t.Elem())
	case *types.Alias:
		f.addImportsForNamedType(t)
	case *types.Named:
		f.addImportsForNamedType(t)
	case *types.Slice:
		f.addImportsFor(t.Elem())
	case *types.Array:
		f.addImportsFor(t.Elem())
	case *types.TypeParam:
		return
	case *types.Union:
		for i := 0; i < t.Len(); i++ {
			f.addImportsFor(t.Term(i).Type())
		}
	case *types.Interface:
		for i := 0; i < t.NumEmbeddeds(); i++ {
			f.addImportsFor(t.EmbeddedType(i))
		}
		for i := 0; i < t.NumExplicitMethods(); i++ {
			f.addImportsFor(t.ExplicitMethod(i).Type())
		}
	case *types.Signature:
		f.addTypesForMethod(t)
	case *types.Struct:
		for i := 0; i < t.NumFields(); i++ {
			f.addImportsFor(t.Field(i).Type())
		}
	default:
		log.Printf("!!! WARNING: Missing case for type %s\n", reflect.TypeOf(typ).String())
	}
}

func (f *Fake) addImportsForNamedType(t interface {
	Obj() *types.TypeName
	TypeArgs() *types.TypeList
}) {
	if t.Obj() != nil && t.Obj().Pkg() != nil {
		typeArgs := t.TypeArgs()
		for i := 0; i < typeArgs.Len(); i++ {
			f.addImportsFor(typeArgs.At(i))
		}
		if f.inTargetPackage && imports.VendorlessPath(t.Obj().Pkg().Path()) == f.TargetPackage {
			return
		}
		f.Imports.Add(t.Obj().Pkg().Name(), t.Obj().Pkg().Path())
	}
}
