package main_test

import (
	"errors"

	"github.com/maxbrunsfeld/counterfeiter/fixtures"
	"github.com/maxbrunsfeld/counterfeiter/fixtures/fakes"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("A Fake generated by counterfeiter", func() {
	var fake *fakes.FakeSomething

	BeforeEach(func() {
		fake = new(fakes.FakeSomething)
	})

	It("implements the interface", func() {
		var someInterface fixtures.Something = fake
		Expect(someInterface).NotTo(BeNil())
	})

	It("can have its behavior configured using stub functions", func() {
		fake.DoThingsStub = func(arg1 string, arg2 uint64) (int, error) {
			Expect(arg1).To(Equal("stuff"))
			Expect(arg2).To(Equal(uint64(5)))
			return 3, errors.New("the-error")
		}

		num, err := fake.DoThings("stuff", 5)

		Expect(num).To(Equal(3))
		Expect(err).To(Equal(errors.New("the-error")))
	})

	It("can have its return values configured", func() {
		fake.DoThingsReturns(3, errors.New("the-error"))

		num, err := fake.DoThings("stuff", 5)
		Expect(num).To(Equal(3))
		Expect(err).To(Equal(errors.New("the-error")))
	})

	It("returns zero values when no return value or stub is provided", func() {
		fake.DoNothing()
		num, err := fake.DoThings("stuff", 5)

		Expect(num).To(Equal(0))
		Expect(err).To(BeNil())
	})

	It("records the arguments it was called with", func() {
		Expect(fake.DoThingsCalls()).To(HaveLen(0))

		fake.DoThings("stuff", 5)

		Expect(fake.DoThingsCalls()).To(HaveLen(1))
		Expect(fake.DoThingsCalls()[0].Arg1).To(Equal("stuff"))
		Expect(fake.DoThingsCalls()[0].Arg2).To(Equal(uint64(5)))
	})

	It("records its calls without race conditions", func() {
		go fake.DoNothing()

		Eventually(fake.DoNothingCalls, 1.0).Should(HaveLen(1))
	})
})
