// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures/generate_defaults"
)

type NotTheRealSong struct {
	SongStub        func() string
	songMutex       sync.RWMutex
	songArgsForCall []struct {
	}
	songReturns struct {
		result1 string
	}
	songReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotTheRealSong) Song() string {
	fake.songMutex.Lock()
	ret, specificReturn := fake.songReturnsOnCall[len(fake.songArgsForCall)]
	fake.songArgsForCall = append(fake.songArgsForCall, struct {
	}{})
	stub := fake.SongStub
	fakeReturns := fake.songReturns
	fake.recordInvocation("Song", []interface{}{})
	fake.songMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *NotTheRealSong) SongCallCount() int {
	fake.songMutex.RLock()
	defer fake.songMutex.RUnlock()
	return len(fake.songArgsForCall)
}

func (fake *NotTheRealSong) SongCalls(stub func() string) {
	fake.songMutex.Lock()
	defer fake.songMutex.Unlock()
	fake.SongStub = stub
}

func (fake *NotTheRealSong) SongReturns(result1 string) {
	fake.songMutex.Lock()
	defer fake.songMutex.Unlock()
	fake.SongStub = nil
	fake.songReturns = struct {
		result1 string
	}{result1}
}

func (fake *NotTheRealSong) SongReturnsOnCall(i int, result1 string) {
	fake.songMutex.Lock()
	defer fake.songMutex.Unlock()
	fake.SongStub = nil
	if fake.songReturnsOnCall == nil {
		fake.songReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.songReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *NotTheRealSong) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.songMutex.RLock()
	defer fake.songMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotTheRealSong) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ generate_defaults.Song = new(NotTheRealSong)
