// Code generated by counterfeiter. DO NOT EDIT.
package hyphenpackage

import (
	"sync"
)

type FakeHyphenated struct {
	HyphenStub        func() string
	hyphenMutex       sync.RWMutex
	hyphenArgsForCall []struct {
	}
	hyphenReturns struct {
		result1 string
	}
	hyphenReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHyphenated) Hyphen() string {
	fake.hyphenMutex.Lock()
	ret, specificReturn := fake.hyphenReturnsOnCall[len(fake.hyphenArgsForCall)]
	fake.hyphenArgsForCall = append(fake.hyphenArgsForCall, struct {
	}{})
	stub := fake.HyphenStub
	fakeReturns := fake.hyphenReturns
	fake.recordInvocation("Hyphen", []interface{}{})
	fake.hyphenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHyphenated) HyphenCallCount() int {
	fake.hyphenMutex.RLock()
	defer fake.hyphenMutex.RUnlock()
	return len(fake.hyphenArgsForCall)
}

func (fake *FakeHyphenated) HyphenCalls(stub func() string) {
	fake.hyphenMutex.Lock()
	defer fake.hyphenMutex.Unlock()
	fake.HyphenStub = stub
}

func (fake *FakeHyphenated) HyphenReturns(result1 string) {
	fake.hyphenMutex.Lock()
	defer fake.hyphenMutex.Unlock()
	fake.HyphenStub = nil
	fake.hyphenReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeHyphenated) HyphenReturnsOnCall(i int, result1 string) {
	fake.hyphenMutex.Lock()
	defer fake.hyphenMutex.Unlock()
	fake.HyphenStub = nil
	if fake.hyphenReturnsOnCall == nil {
		fake.hyphenReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.hyphenReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeHyphenated) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHyphenated) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ Hyphenated = new(FakeHyphenated)
