// Code generated by counterfeiter. DO NOT EDIT.
package fixturesfakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures"
)

type FakeHasVarArgsWithLocalTypes struct {
	DoThingsStub        func(...fixtures.LocalType)
	doThingsMutex       sync.RWMutex
	doThingsArgsForCall []FakeHasVarArgsWithLocalTypesDoThingsArgs
	invocations         map[string][][]interface{}
	callOrder           []string
	invocationsMutex    sync.RWMutex
}

// FakeHasVarArgsWithLocalTypesDoThingsArgs holds the arguments of one call to DoThings.
type FakeHasVarArgsWithLocalTypesDoThingsArgs struct {
	Arg1 []fixtures.LocalType
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThings(arg1 ...fixtures.LocalType) {
	var arg1Copy []fixtures.LocalType
	if arg1 != nil {
		arg1Copy = make([]fixtures.LocalType, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.doThingsMutex.Lock()
	fake.doThingsArgsForCall = append(fake.doThingsArgsForCall, FakeHasVarArgsWithLocalTypesDoThingsArgs{arg1Copy})
	stub := fake.DoThingsStub
	fake.recordInvocation("DoThings", []interface{}{arg1Copy})
	fake.doThingsMutex.Unlock()
	if stub != nil {
		stub(arg1...)
	}
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsCallCount() int {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	return len(fake.doThingsArgsForCall)
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsCalls(stub func(...fixtures.LocalType)) {
	fake.doThingsMutex.Lock()
	defer fake.doThingsMutex.Unlock()
	fake.DoThingsStub = stub
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsArgsForCall(i int) []fixtures.LocalType {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	argsForCall := fake.doThingsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsArgs() []FakeHasVarArgsWithLocalTypesDoThingsArgs {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	args := make([]FakeHasVarArgsWithLocalTypesDoThingsArgs, len(fake.doThingsArgsForCall))
	copy(args, fake.doThingsArgsForCall)
	return args
}

func (fake *FakeHasVarArgsWithLocalTypes) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHasVarArgsWithLocalTypes) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeHasVarArgsWithLocalTypes) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fixtures.HasVarArgsWithLocalTypes = new(FakeHasVarArgsWithLocalTypes)
