// Code generated by counterfeiter. DO NOT EDIT.
package fixturesfakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures"
)

type FakeNotifier struct {
	Stub             func(string)
	mutex            sync.RWMutex
	argsForCall      []FakeNotifierArgs
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

// FakeNotifierArgs holds the arguments of one call to the fake.
type FakeNotifierArgs struct {
	Arg1 string
}

func (fake *FakeNotifier) Spy(arg1 string) {
	fake.mutex.Lock()
	fake.argsForCall = append(fake.argsForCall, FakeNotifierArgs{arg1})
	stub := fake.Stub
	fake.recordInvocation("Notifier", []interface{}{arg1})
	fake.mutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *FakeNotifier) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeNotifier) Calls(stub func(string)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeNotifier) ArgsForCall(i int) string {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].Arg1
}

func (fake *FakeNotifier) Args() []FakeNotifierArgs {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	args := make([]FakeNotifierArgs, len(fake.argsForCall))
	copy(args, fake.argsForCall)
	return args
}

func (fake *FakeNotifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNotifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fixtures.Notifier = new(FakeNotifier).Spy
