// Code generated by counterfeiter. DO NOT EDIT.
package fixturesfakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures"
)

type FakeHasVarArgs struct {
	DoMoreThingsStub        func(int, int, ...string) int
	doMoreThingsMutex       sync.RWMutex
	doMoreThingsArgsForCall []FakeHasVarArgsDoMoreThingsArgs
	doMoreThingsReturns     struct {
		result1 int
	}
	doMoreThingsReturnsOnCall map[int]struct {
		result1 int
	}
	DoThingsStub        func(int, ...string) int
	doThingsMutex       sync.RWMutex
	doThingsArgsForCall []FakeHasVarArgsDoThingsArgs
	doThingsReturns     struct {
		result1 int
	}
	doThingsReturnsOnCall map[int]struct {
		result1 int
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeHasVarArgsDoMoreThingsArgs holds the arguments of one call to DoMoreThings.
type FakeHasVarArgsDoMoreThingsArgs struct {
	Arg1 int
	Arg2 int
	Arg3 []string
}

// FakeHasVarArgsDoThingsArgs holds the arguments of one call to DoThings.
type FakeHasVarArgsDoThingsArgs struct {
	Arg1 int
	Arg2 []string
}

func (fake *FakeHasVarArgs) DoMoreThings(arg1 int, arg2 int, arg3 ...string) int {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.doMoreThingsMutex.Lock()
	ret, specificReturn := fake.doMoreThingsReturnsOnCall[len(fake.doMoreThingsArgsForCall)]
	fake.doMoreThingsArgsForCall = append(fake.doMoreThingsArgsForCall, FakeHasVarArgsDoMoreThingsArgs{arg1, arg2, arg3Copy})
	stub := fake.DoMoreThingsStub
	fakeReturns := fake.doMoreThingsReturns
	fake.recordInvocation("DoMoreThings", []interface{}{arg1, arg2, arg3Copy})
	fake.doMoreThingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHasVarArgs) DoMoreThingsCallCount() int {
	fake.doMoreThingsMutex.RLock()
	defer fake.doMoreThingsMutex.RUnlock()
	return len(fake.doMoreThingsArgsForCall)
}

func (fake *FakeHasVarArgs) DoMoreThingsCalls(stub func(int, int, ...string) int) {
	fake.doMoreThingsMutex.Lock()
	defer fake.doMoreThingsMutex.Unlock()
	fake.DoMoreThingsStub = stub
}

func (fake *FakeHasVarArgs) DoMoreThingsArgsForCall(i int) (int, int, []string) {
	fake.doMoreThingsMutex.RLock()
	defer fake.doMoreThingsMutex.RUnlock()
	argsForCall := fake.doMoreThingsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeHasVarArgs) DoMoreThingsArgs() []FakeHasVarArgsDoMoreThingsArgs {
	fake.doMoreThingsMutex.RLock()
	defer fake.doMoreThingsMutex.RUnlock()
	args := make([]FakeHasVarArgsDoMoreThingsArgs, len(fake.doMoreThingsArgsForCall))
	copy(args, fake.doMoreThingsArgsForCall)
	return args
}

func (fake *FakeHasVarArgs) DoMoreThingsReturns(result1 int) {
	fake.doMoreThingsMutex.Lock()
	defer fake.doMoreThingsMutex.Unlock()
	fake.DoMoreThingsStub = nil
	fake.doMoreThingsReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeHasVarArgs) DoMoreThingsReturnsOnCall(i int, result1 int) {
	fake.doMoreThingsMutex.Lock()
	defer fake.doMoreThingsMutex.Unlock()
	fake.DoMoreThingsStub = nil
	if fake.doMoreThingsReturnsOnCall == nil {
		fake.doMoreThingsReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.doMoreThingsReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeHasVarArgs) DoThings(arg1 int, arg2 ...string) int {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.doThingsMutex.Lock()
	ret, specificReturn := fake.doThingsReturnsOnCall[len(fake.doThingsArgsForCall)]
	fake.doThingsArgsForCall = append(fake.doThingsArgsForCall, FakeHasVarArgsDoThingsArgs{arg1, arg2Copy})
	stub := fake.DoThingsStub
	fakeReturns := fake.doThingsReturns
	fake.recordInvocation("DoThings", []interface{}{arg1, arg2Copy})
	fake.doThingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHasVarArgs) DoThingsCallCount() int {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	return len(fake.doThingsArgsForCall)
}

func (fake *FakeHasVarArgs) DoThingsCalls(stub func(int, ...string) int) {
	fake.doThingsMutex.Lock()
	defer fake.doThingsMutex.Unlock()
	fake.DoThingsStub = stub
}

func (fake *FakeHasVarArgs) DoThingsArgsForCall(i int) (int, []string) {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	argsForCall := fake.doThingsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeHasVarArgs) DoThingsArgs() []FakeHasVarArgsDoThingsArgs {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	args := make([]FakeHasVarArgsDoThingsArgs, len(fake.doThingsArgsForCall))
	copy(args, fake.doThingsArgsForCall)
	return args
}

func (fake *FakeHasVarArgs) DoThingsReturns(result1 int) {
	fake.doThingsMutex.Lock()
	defer fake.doThingsMutex.Unlock()
	fake.DoThingsStub = nil
	fake.doThingsReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeHasVarArgs) DoThingsReturnsOnCall(i int, result1 int) {
	fake.doThingsMutex.Lock()
	defer fake.doThingsMutex.Unlock()
	fake.DoThingsStub = nil
	if fake.doThingsReturnsOnCall == nil {
		fake.doThingsReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.doThingsReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeHasVarArgs) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHasVarArgs) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeHasVarArgs) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fixtures.HasVarArgs = new(FakeHasVarArgs)
