// Code generated by counterfeiter. DO NOT EDIT.
package fixturesfakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/v6/fixtures"
)

type FakeSomethingFactory struct {
	Stub        func(string, map[string]interface{}) string
	mutex       sync.RWMutex
	argsForCall []FakeSomethingFactoryArgs
	returns     struct {
		result1 string
	}
	returnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

// FakeSomethingFactoryArgs holds the arguments of one call to the fake.
type FakeSomethingFactoryArgs struct {
	Arg1 string
	Arg2 map[string]interface{}
}

func (fake *FakeSomethingFactory) Spy(arg1 string, arg2 map[string]interface{}) string {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, FakeSomethingFactoryArgs{arg1, arg2})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("SomethingFactory", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *FakeSomethingFactory) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeSomethingFactory) Calls(stub func(string, map[string]interface{}) string) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeSomethingFactory) ArgsForCall(i int) (string, map[string]interface{}) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].Arg1, fake.argsForCall[i].Arg2
}

func (fake *FakeSomethingFactory) Args() []FakeSomethingFactoryArgs {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	args := make([]FakeSomethingFactoryArgs, len(fake.argsForCall))
	copy(args, fake.argsForCall)
	return args
}

func (fake *FakeSomethingFactory) Returns(result1 string) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSomethingFactory) ReturnsOnCall(i int, result1 string) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSomethingFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSomethingFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fixtures.SomethingFactory = new(FakeSomethingFactory).Spy
