// Code generated by counterfeiter. DO NOT EDIT.
package externaltest_test

import (
	"sync"

	"github.com/onsi/gomega/types"
)

type FakeGomegaMatcher struct {
	FailureMessageStub        func(any) string
	failureMessageMutex       sync.RWMutex
	failureMessageArgsForCall []struct {
		arg1 any
	}
	failureMessageReturns struct {
		result1 string
	}
	failureMessageReturnsOnCall map[int]struct {
		result1 string
	}
	MatchStub        func(any) (bool, error)
	matchMutex       sync.RWMutex
	matchArgsForCall []struct {
		arg1 any
	}
	matchReturns struct {
		result1 bool
		result2 error
	}
	matchReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	NegatedFailureMessageStub        func(any) string
	negatedFailureMessageMutex       sync.RWMutex
	negatedFailureMessageArgsForCall []struct {
		arg1 any
	}
	negatedFailureMessageReturns struct {
		result1 string
	}
	negatedFailureMessageReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGomegaMatcher) FailureMessage(arg1 any) string {
	fake.failureMessageMutex.Lock()
	ret, specificReturn := fake.failureMessageReturnsOnCall[len(fake.failureMessageArgsForCall)]
	fake.failureMessageArgsForCall = append(fake.failureMessageArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.FailureMessageStub
	fakeReturns := fake.failureMessageReturns
	fake.recordInvocation("FailureMessage", []interface{}{arg1})
	fake.failureMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGomegaMatcher) FailureMessageCallCount() int {
	fake.failureMessageMutex.RLock()
	defer fake.failureMessageMutex.RUnlock()
	return len(fake.failureMessageArgsForCall)
}

func (fake *FakeGomegaMatcher) FailureMessageCalls(stub func(any) string) {
	fake.failureMessageMutex.Lock()
	defer fake.failureMessageMutex.Unlock()
	fake.FailureMessageStub = stub
}

func (fake *FakeGomegaMatcher) FailureMessageArgsForCall(i int) any {
	fake.failureMessageMutex.RLock()
	defer fake.failureMessageMutex.RUnlock()
	argsForCall := fake.failureMessageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGomegaMatcher) FailureMessageReturns(result1 string) {
	fake.failureMessageMutex.Lock()
	defer fake.failureMessageMutex.Unlock()
	fake.FailureMessageStub = nil
	fake.failureMessageReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGomegaMatcher) FailureMessageReturnsOnCall(i int, result1 string) {
	fake.failureMessageMutex.Lock()
	defer fake.failureMessageMutex.Unlock()
	fake.FailureMessageStub = nil
	if fake.failureMessageReturnsOnCall == nil {
		fake.failureMessageReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.failureMessageReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGomegaMatcher) Match(arg1 any) (bool, error) {
	fake.matchMutex.Lock()
	ret, specificReturn := fake.matchReturnsOnCall[len(fake.matchArgsForCall)]
	fake.matchArgsForCall = append(fake.matchArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.MatchStub
	fakeReturns := fake.matchReturns
	fake.recordInvocation("Match", []interface{}{arg1})
	fake.matchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGomegaMatcher) MatchCallCount() int {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return len(fake.matchArgsForCall)
}

func (fake *FakeGomegaMatcher) MatchCalls(stub func(any) (bool, error)) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = stub
}

func (fake *FakeGomegaMatcher) MatchArgsForCall(i int) any {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	argsForCall := fake.matchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGomegaMatcher) MatchReturns(result1 bool, result2 error) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	fake.matchReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGomegaMatcher) MatchReturnsOnCall(i int, result1 bool, result2 error) {
	fake.matchMutex.Lock()
	defer fake.matchMutex.Unlock()
	fake.MatchStub = nil
	if fake.matchReturnsOnCall == nil {
		fake.matchReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.matchReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGomegaMatcher) NegatedFailureMessage(arg1 any) string {
	fake.negatedFailureMessageMutex.Lock()
	ret, specificReturn := fake.negatedFailureMessageReturnsOnCall[len(fake.negatedFailureMessageArgsForCall)]
	fake.negatedFailureMessageArgsForCall = append(fake.negatedFailureMessageArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.NegatedFailureMessageStub
	fakeReturns := fake.negatedFailureMessageReturns
	fake.recordInvocation("NegatedFailureMessage", []interface{}{arg1})
	fake.negatedFailureMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGomegaMatcher) NegatedFailureMessageCallCount() int {
	fake.negatedFailureMessageMutex.RLock()
	defer fake.negatedFailureMessageMutex.RUnlock()
	return len(fake.negatedFailureMessageArgsForCall)
}

func (fake *FakeGomegaMatcher) NegatedFailureMessageCalls(stub func(any) string) {
	fake.negatedFailureMessageMutex.Lock()
	defer fake.negatedFailureMessageMutex.Unlock()
	fake.NegatedFailureMessageStub = stub
}

func (fake *FakeGomegaMatcher) NegatedFailureMessageArgsForCall(i int) any {
	fake.negatedFailureMessageMutex.RLock()
	defer fake.negatedFailureMessageMutex.RUnlock()
	argsForCall := fake.negatedFailureMessageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGomegaMatcher) NegatedFailureMessageReturns(result1 string) {
	fake.negatedFailureMessageMutex.Lock()
	defer fake.negatedFailureMessageMutex.Unlock()
	fake.NegatedFailureMessageStub = nil
	fake.negatedFailureMessageReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeGomegaMatcher) NegatedFailureMessageReturnsOnCall(i int, result1 string) {
	fake.negatedFailureMessageMutex.Lock()
	defer fake.negatedFailureMessageMutex.Unlock()
	fake.NegatedFailureMessageStub = nil
	if fake.negatedFailureMessageReturnsOnCall == nil {
		fake.negatedFailureMessageReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.negatedFailureMessageReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeGomegaMatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGomegaMatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.GomegaMatcher = new(FakeGomegaMatcher)
