// This file was generated by counterfeiter
package fakes

import "sync"

type FakeUnexportedInterface struct {
	SomeMethodStub        func(string, bool) (int, error)
	someMethodMutex       sync.RWMutex
	someMethodArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	someMethodReturns struct {
		result1 int
		result2 error
	}
}

func (fake *FakeUnexportedInterface) SomeMethod(arg1 string, arg2 bool) (int, error) {
	fake.someMethodMutex.Lock()
	fake.someMethodArgsForCall = append(fake.someMethodArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	fake.someMethodMutex.Unlock()
	if fake.SomeMethodStub != nil {
		return fake.SomeMethodStub(arg1, arg2)
	} else {
		return fake.someMethodReturns.result1, fake.someMethodReturns.result2
	}
}

func (fake *FakeUnexportedInterface) SomeMethodCallCount() int {
	fake.someMethodMutex.RLock()
	defer fake.someMethodMutex.RUnlock()
	return len(fake.someMethodArgsForCall)
}

func (fake *FakeUnexportedInterface) SomeMethodArgsForCall(i int) (string, bool) {
	fake.someMethodMutex.RLock()
	defer fake.someMethodMutex.RUnlock()
	return fake.someMethodArgsForCall[i].arg1, fake.someMethodArgsForCall[i].arg2
}

func (fake *FakeUnexportedInterface) SomeMethodReturns(result1 int, result2 error) {
	fake.SomeMethodStub = nil
	fake.someMethodReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}
