// This file was generated by counterfeiter
package fakes

import (
	"sync"

	. "github.com/maxbrunsfeld/counterfeiter/fixtures"
)

type FakeHasOtherTypes struct {
	GetThingStub        func(SomeString) SomeFunc
	getThingMutex       sync.RWMutex
	getThingArgsForCall []struct {
		arg1 SomeString
	}
	getThingReturns struct {
		result1 SomeFunc
	}
}

func (fake *FakeHasOtherTypes) GetThing(arg1 SomeString) SomeFunc {
	fake.getThingMutex.Lock()
	defer fake.getThingMutex.Unlock()
	fake.getThingArgsForCall = append(fake.getThingArgsForCall, struct {
		arg1 SomeString
	}{arg1})
	if fake.GetThingStub != nil {
		return fake.GetThingStub(arg1)
	} else {
		return fake.getThingReturns.result1
	}
}

func (fake *FakeHasOtherTypes) GetThingCallCount() int {
	fake.getThingMutex.RLock()
	defer fake.getThingMutex.RUnlock()
	return len(fake.getThingArgsForCall)
}

func (fake *FakeHasOtherTypes) GetThingArgsForCall(i int) SomeString {
	fake.getThingMutex.RLock()
	defer fake.getThingMutex.RUnlock()
	return fake.getThingArgsForCall[i].arg1
}

func (fake *FakeHasOtherTypes) GetThingReturns(result1 SomeFunc) {
	fake.getThingReturns = struct {
		result1 SomeFunc
	}{result1}
}

var _ HasOtherTypes = new(FakeHasOtherTypes)
