// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/maxbrunsfeld/counterfeiter/fixtures"
)

type FakeHasVarArgsWithLocalTypes struct {
	DoThingsStub        func(...fixtures.LocalType)
	doThingsMutex       sync.RWMutex
	doThingsArgsForCall []struct {
		arg1 []fixtures.LocalType
	}
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThings(arg1 ...fixtures.LocalType) {
	fake.doThingsMutex.Lock()
	fake.doThingsArgsForCall = append(fake.doThingsArgsForCall, struct {
		arg1 []fixtures.LocalType
	}{arg1})
	fake.doThingsMutex.Unlock()
	if fake.DoThingsStub != nil {
		fake.DoThingsStub(arg1...)
	}
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsCallCount() int {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	return len(fake.doThingsArgsForCall)
}

func (fake *FakeHasVarArgsWithLocalTypes) DoThingsArgsForCall(i int) []fixtures.LocalType {
	fake.doThingsMutex.RLock()
	defer fake.doThingsMutex.RUnlock()
	return fake.doThingsArgsForCall[i].arg1
}

var _ fixtures.HasVarArgsWithLocalTypes = new(FakeHasVarArgsWithLocalTypes)
