package integration_test

import (
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/onsi/gomega/gbytes"
	"github.com/onsi/gomega/gexec"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("The counterfeiter CLI", func() {
	var pathToCLI string

	BeforeEach(func() {
		pathToCLI = tmpPath("counterfeiter")
	})

	It("can generate a fake for a typed function", func() {
		copyIn("typed_function.go", pathToCLI)

		session := startCounterfeiter(pathToCLI, "typed_function.go", "SomethingFactory")

		Eventually(session).Should(gexec.Exit(0))
		Eventually(session).Should(gbytes.Say("Wrote `FakeSomethingFactory"))
	})

	Describe("when given a single argument", func() {
		It("interactively prompts the user for the interface they want to counterfeit", func() {
			reader, writer := io.Pipe()

			copyIn("multiple_interfaces.go", pathToCLI)
			session := startCounterfeiterWithStdinPipe(pathToCLI, reader, "multiple_interfaces.go")

			writer.Write([]byte("1\n"))
			writer.Close()

			Eventually(session).Should(gexec.Exit(0))
			Expect(string(session.Out.Contents())).To(ContainSubstring("Wrote `FakeFirstInterface`"))
		})
	})

	Describe("when given two arguments", func() {
		BeforeEach(func() {
			copyIn("something.go", pathToCLI)
		})

		It("writes a fake for the given interface from the provided file", func() {
			session := startCounterfeiter(pathToCLI, "something.go", "Something")

			Eventually(session).Should(gexec.Exit(0))
			output := string(session.Out.Contents())

			Expect(output).To(ContainSubstring("Wrote `FakeSomething`"))
		})
	})

	Describe("when provided three arguments", func() {
		BeforeEach(func() {
			copyIn("something.go", pathToCLI)
		})

		It("writes the fake to stdout", func() {
			session := startCounterfeiter(pathToCLI, "something.go", "Something", "-")

			Eventually(session).Should(gexec.Exit(0))
			output := string(session.Out.Contents())

			Expect(output).To(ContainSubstring("// This file was generated by counterfeiter"))
		})
	})
})

// helper functions

func tmpPath(destination string) string {
	return filepath.Join(tmpDir, "src", destination)
}

func copyIn(fixture string, destination string) {
	err := os.MkdirAll(destination, 0777)
	Expect(err).ToNot(HaveOccurred())

	filepath.Walk(filepath.Join("..", "fixtures", fixture), func(path string, info os.FileInfo, err error) error {
		if info.IsDir() {
			return nil
		}

		base := filepath.Base(path)

		src, err := os.Open(path)
		Expect(err).ToNot(HaveOccurred())

		dst, err := os.Create(filepath.Join(destination, base))
		Expect(err).ToNot(HaveOccurred())

		_, err = io.Copy(dst, src)
		Expect(err).ToNot(HaveOccurred())
		return nil
	})
}

func startCounterfeiter(workingDir string, args ...string) *gexec.Session {
	fakeGoPathDir := filepath.Dir(filepath.Dir(workingDir))
	absPath, _ := filepath.Abs(fakeGoPathDir)
	absPathWithSymlinks, _ := filepath.EvalSymlinks(absPath)

	cmd := exec.Command(pathToCounterfeiter, args...)
	cmd.Dir = workingDir
	cmd.Env = []string{"GOPATH=" + absPathWithSymlinks}

	session, err := gexec.Start(cmd, GinkgoWriter, GinkgoWriter)
	Expect(err).ToNot(HaveOccurred())
	return session
}

func startCounterfeiterWithStdinPipe(workingDir string, stdin io.Reader, args ...string) *gexec.Session {
	fakeGoPathDir := filepath.Dir(filepath.Dir(workingDir))
	absPath, _ := filepath.Abs(fakeGoPathDir)
	absPathWithSymlinks, _ := filepath.EvalSymlinks(absPath)

	cmd := exec.Command(pathToCounterfeiter, args...)
	cmd.Stdin = stdin
	cmd.Dir = workingDir
	cmd.Env = []string{
		"GOPATH=" + absPathWithSymlinks,
		"COUNTERFEITER_INTERACTIVE=1",
	}

	session, err := gexec.Start(cmd, GinkgoWriter, GinkgoWriter)
	Expect(err).ToNot(HaveOccurred())
	return session
}

// gexec setup

var tmpDir string
var pathToCounterfeiter string

var _ = SynchronizedBeforeSuite(func() []byte {
	pathToCounterfeiter, err := gexec.Build("github.com/maxbrunsfeld/counterfeiter")
	Expect(err).ToNot(HaveOccurred())
	return []byte(pathToCounterfeiter)
}, func(computedPath []byte) {
	pathToCounterfeiter = string(computedPath)
})

var _ = SynchronizedAfterSuite(func() {}, func() {
	gexec.CleanupBuildArtifacts()
})

var _ = BeforeEach(func() {
	var err error
	tmpDir, err = ioutil.TempDir("", "counterfeiter-integration")
	Expect(err).ToNot(HaveOccurred())
})

var _ = AfterEach(func() {
	err := os.RemoveAll(tmpDir)
	Expect(err).ToNot(HaveOccurred())
})
