// Code generated by counterfeiter. DO NOT EDIT.
package samepackage

import (
	"sync"
)

type fakeGadget struct {
	SpinStub        func(int) error
	spinMutex       sync.RWMutex
	spinArgsForCall []struct {
		arg1 int
	}
	spinReturns struct {
		result1 error
	}
	spinReturnsOnCall map[int]struct {
		result1 error
	}
	stopStub        func()
	stopMutex       sync.RWMutex
	stopArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *fakeGadget) Spin(arg1 int) error {
	fake.spinMutex.Lock()
	ret, specificReturn := fake.spinReturnsOnCall[len(fake.spinArgsForCall)]
	fake.spinArgsForCall = append(fake.spinArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.SpinStub
	fakeReturns := fake.spinReturns
	fake.recordInvocation("Spin", []interface{}{arg1})
	fake.spinMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *fakeGadget) SpinCallCount() int {
	fake.spinMutex.RLock()
	defer fake.spinMutex.RUnlock()
	return len(fake.spinArgsForCall)
}

func (fake *fakeGadget) SpinCalls(stub func(int) error) {
	fake.spinMutex.Lock()
	defer fake.spinMutex.Unlock()
	fake.SpinStub = stub
}

func (fake *fakeGadget) SpinArgsForCall(i int) int {
	fake.spinMutex.RLock()
	defer fake.spinMutex.RUnlock()
	argsForCall := fake.spinArgsForCall[i]
	return argsForCall.arg1
}

func (fake *fakeGadget) SpinReturns(result1 error) {
	fake.spinMutex.Lock()
	defer fake.spinMutex.Unlock()
	fake.SpinStub = nil
	fake.spinReturns = struct {
		result1 error
	}{result1}
}

func (fake *fakeGadget) SpinReturnsOnCall(i int, result1 error) {
	fake.spinMutex.Lock()
	defer fake.spinMutex.Unlock()
	fake.SpinStub = nil
	if fake.spinReturnsOnCall == nil {
		fake.spinReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.spinReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *fakeGadget) stop() {
	fake.stopMutex.Lock()
	fake.stopArgsForCall = append(fake.stopArgsForCall, struct {
	}{})
	stub := fake.stopStub
	fake.recordInvocation("stop", []interface{}{})
	fake.stopMutex.Unlock()
	if stub != nil {
		stub()
	}
}

func (fake *fakeGadget) StopCallCount() int {
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	return len(fake.stopArgsForCall)
}

func (fake *fakeGadget) StopCalls(stub func()) {
	fake.stopMutex.Lock()
	defer fake.stopMutex.Unlock()
	fake.stopStub = stub
}

func (fake *fakeGadget) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *fakeGadget) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gadget = new(fakeGadget)
